### ISSUE TITLE
Timeout error on large mods

### ISSUE THREAD

**Issue by eric963** [alec-hs/Flaxs-Arma-Server-Tool#12]
Getting these type error on large downloads like CUP-Terrains and RHS stuff..

Downloading item 583496184 ...ERROR! Timeout downloading item 583496184

I am doing the initial updates.  Smaller mods I have no issues and also no issues if I use steamcmd to download them.

Not sure if its a steam generated message or related to your great little program.

Thanks
Eric

**Comment by alec-hs** [comment]
Thanks for the report - it's a steam issue unfortunately. Large downloads on slower connections time out. I will add some handling in to make sure the mod downloads. 

Right now if you just press update again it will pick up where the download left off last time.

**Comment by eric963** [comment]
Sounds good!! THX

**Comment by alec-hs** [comment]
Cannot fix due to steam limitation.
