### ISSUE TITLE
Special character : preventing symbolic link

### ISSUE THREAD

**Issue by eric963** [alec-hs/Flaxs-Arma-Server-Tool#13]
MOD 884966711
Name shown in FAST - ACE Compat - RHS: GREF

Any way to edit the mod name before we update?  Or should I just set it as a private mod and put a new mod name in there?

**Comment by alec-hs** [comment]
Yea - just open the mods.cfg file in the exe location and remove the offending character. Is it the ":" that caused it?

**Comment by eric963** [comment]
Pretty sure that's the character.  Tried to make a folder with it and it would not let me use it.  Downloading big mod right now, ill edit the file when its done and let you know for sure.

**Comment by eric963** [comment]
Yep, that did it.

**Comment by alec-hs** [comment]
Great thanks - will add a correction to remove the offending character.

**Comment by eric963** [comment]
The mod Kunduz, Afghanistan has a comma in it and was causing many errors.

Here are a couple more that can not be used in folder names.
\
/
:
*
?
"
<
>

**Comment by alec-hs** [comment]
Cheers - all will be added.
