### ISSUE TITLE
MOD stays orange after update

### ISSUE THREAD

**Issue by eric963** [alec-hs/Flaxs-Arma-Server-Tool#14]
Had a mod show up as having an update ready and its bar war orange.  Did the update and its bar stayed orange.  Here is the line from the mods.cfg

949252631,Arma 3 Aegis (Alpha),7/18/2017 9:32:22 PM,7/18/2017 10:42:41 PM,public

I think it has something to do with the mods update time.  You can see where I did the update at 7/18/2017 9:32:22 PM and I assume the second time the 7/18/2017 10:42 PM is the update date/time from the mod.  Since its showing a later time the when I did the update I think that's whats causing it to stay orange.

**Comment by alec-hs** [comment]
Fixed in 2.0
