### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by flexgrip** [alec-hs/Flaxs-Arma-Server-Tool#16]
Hey man. Looks like a really cool tool.

I'm wondering if you have any tips or success running this app via mono. I'd like to see if it would work with Linux.

Mono has a vb compiler since 1.2.something.

If you've not given this much though, I'll try it out myself and submit any pull requests needed to make it work. I steer far away from .NET stuff, but your code is readable enough that I can probably grind my way through it. If all else fails, maybe wine?

Thanks for any help you can give me!

**Comment by alec-hs** [comment]
Not tried or even given it a thought to be honest. Would most probably require a full rewrite for Linux due to the fact it uses SteamCMD for windows and a load of other Windows only things. Maybe one day I'll port it.

**Comment by flexgrip** [comment]
Thanks! Steamcmd works fine on Linux. And there are several supporting tools for it.

Getting ready to try it. I'll report back in.
