### ISSUE TITLE
MODS not loading

### ISSUE THREAD

**Issue by eric963** [alec-hs/Flaxs-Arma-Server-Tool#19]
I am attaching the rpt file.  You can see on line 3 the mods that are supposed to be loaded by they don't.

Only difference I can see between this report and the on that does work with TADST is your generated config line uses -mods" and TADST uses -mod=

here is the rpt file 
[arma3server_x64_2017-09-26_21-18-59.zip](https://github.com/alec-hs/Flaxs-Arma-Server-Tool/files/1335466/arma3server_x64_2017-09-26_21-18-59.zip)

**Comment by eric963** [comment]
Also on line 509 this is coming up

File G:\Games\Flax Server Tool\servers\test\Users\test\test.Arma3Profile, line 1: '.difficulty': Missing ';' at the end of line

**Comment by alec-hs** [comment]
Moved deleted comment to #20

**Comment by alec-hs** [comment]
Beta Release binaries now have fix included.
