### ISSUE TITLE
Arma3Profile write issue.

### ISSUE THREAD

**Issue by alec-hs** [alec-hs/Flaxs-Arma-Server-Tool#20]
File G:\Games\Flax Server Tool\servers\test\Users\test\test.Arma3Profile, line 1: '.difficulty': Missing ';' at the end of line.

**Comment by alec-hs** [comment]
Can you link a pastebin of the content of that file? I'm trying to replicate but can't repeat the issue.

**Comment by eric963** [comment]
As soon as I get home I’ll upload it.

**Comment by eric963** [comment]
I found out how to replicate it.  It happens if you start the program and then change the difficulty preset from its current default setting to another and then launching the server without saving that profile.

**Comment by eric963** [comment]
Now I'm not sure.  Used the new beta and started fresh and no matter what I select I get the same error.

Here is what the first line of my New_Server.Arma3Profile looks like.  It does not matter if I use Recruit, Regular, Veteran or custom its always missing the ; from the end.

difficulty = "Regular"
class DifficultyPresets {
class CustomDifficulty {
class Options {
reduceDamage = 0;
groupIndicators = 0;
friendlyTags = 0;
enemyTags = 0;
detectedMines = 0;
commands = 0;
waypoints = 0;
tacticalPing = 0;
weaponInfo = 0;
stanceIndicator = 0;
staminaBar = 0;
weaponCrosshair = 0;
visionAid = 0;
thirdPersonView = 0;
cameraShake = 0;
scoreTable = 0;
deathMessages = 0;
vonID = 0;
mapContent = 0;
autoReport = 0;
multipleSaves = 0;
};
aiLevelPreset = 3;
class CustomAILevel {
skillAI = 0.75;
precisionAI = 0.40;
};
};
};


Here is a dropbox link to the the file  [New_Server.Arma3Profile](https://www.dropbox.com/s/80d9ibvujtrkuur/New_Server.Arma3Profile?dl=0)

**Comment by alec-hs** [comment]
Ah yea - the string writer is missing the extra ";". I'll fix this now.
