### ISSUE TITLE
Check for Updates - String to Double error

### ISSUE THREAD

**Issue by ryanparsons7** [alec-hs/Flaxs-Arma-Server-Tool#34]
Have 57 Mods in the mod list. Below is an image of the error that occurs when it starts checking for mod updates immediately after starting up.
![image](https://user-images.githubusercontent.com/13571100/38698689-d84c93a0-3e8d-11e8-8831-82c4a764c8d0.png)

This is my mod.cfg that causes the issue to occur:
[mods.txt](https://github.com/alec-hs/Flaxs-Arma-Server-Tool/files/1904616/mods.txt)

Running latest version of the tool (1.3)

EDIT: This occurs on the previous stable version (1.1.2) too, and has only started to occur recently. Tested on my local machine and has the same issue when adding any mod and restarting the tool

**Comment by AtwaterRealty** [comment]
Did we get this resolved? I have the same issue. Any Research I find leads me to this and I dont see a solution...

**Comment by Ztrack** [comment]
Fix can be found here by user suprsurfr
https://forums.bohemia.net/forums/topic/206609-flaxs-arma-server-tool-fast/?page=5

**Comment by alec-hs** [comment]
Issue with the data returned from SteamAPI web query.

**Comment by alec-hs** [comment]
Fixed in [commit](https://github.com/alec-hs/Flaxs-Arma-Server-Tool/commit/b6778091bd74ca02ad4513a90782ce225f56d2db)
