### ISSUE TITLE
Min bandwidth / max bandwith don't use same units

### ISSUE THREAD

**Issue by zocat64** [alec-hs/Flaxs-Arma-Server-Tool#46]
This is a minor issue, but still irritating nonetheless. It's far less confusing to use either both kbit/s or both mbit/s for these two config boxes.

**Comment by AlessandroRomanelli** [comment]
It's actually MUCH worse than this.
Besides having different units, which, to some extent, some of us might be able to deal with, there is a MASSIVE issue with the fact that both fields are label with 'kbps' and 'mbps', when actually these two fields get pasted in the config without any kind of conversion.

Ignore the labels entirely: set both fields using BITS PER SECOND or you'll restrict your bandwidth

**Comment by alec-hs** [comment]
Bit ott with the ALL CAPS it's only a bug report not the end of the world... 😂 

Fixed in 2.0
