### ISSUE TITLE
Feature request for 2.0 Auto restart 

### ISSUE THREAD

**Issue by Doorstop2** [alec-hs/Flaxs-Arma-Server-Tool#48]
For 2.0 it would be nice to have a auto restart being able to set the restart everyday or week/month at certain times including headless clients. 

For example i would like to set my server to restart both the server and headless clients i have 3 every 16 hours. This helps dump the memory as over time the server and headless clients will eat ram requiring a restart to dump the ram.

**Comment by alec-hs** [comment]
Added in 2.0
