### ISSUE TITLE
Endless Loading Screen caused by generated server config

### ISSUE THREAD

**Issue by MoonlightGamingEu** [alec-hs/Flaxs-Arma-Server-Tool#53]
Created a new Server, running the server with this tool results for the client users to get stuck in endless loading screen.
When running the arma3server.exe without the tool, clients do not get stuck while loading.

I am willing to give access to the Server for further testing, since its just a VM I mess around with.
No mods, no fancy stuff, just a fresh new vanilla server.

**Comment by MoonlightGamingEu** [comment]
note here, this also happens with the TADST tool.

**Comment by MoonlightGamingEu** [comment]
A lot of debugging later.
This issue seems to come from one of these starting options.
-port=2302 "-config=C:\Games\ArmA3\A3Master\servers\MoonSim\MoonSim_config.cfg" "-cfg=C:\Games\ArmA3\A3Master\servers\MoonSim\MoonSim_basic.cfg" "-profiles=C:\Games\ArmA3\A3Master\servers\MoonSim\" -name=MoonSim

Will report back asap
EDIT:
Its something with the MoonSim_config.cfg testing more

**Comment by MoonlightGamingEu** [comment]
This is the generated, not working conifg.
```
passwordAdmin = "";
password = "";
serverCommandPassword = "";
hostname = "DEV";
maxPlayers = 18;
kickduplicate = 1;
upnp = 0;
allowedFilePatching = 0;
verifySignatures = 0;
disableVoN = 0;
vonCodecQuality = 30;
vonCodec = 1;
BattlEye = 0;
persistent = 1;
motd[]= {
"MSG",
};
motdInterval = 5;
voteMissionPlayers = 3;
voteThreshold = 33;
doubleIdDetected = "";
onUserConnected = "";
onUserDisconnected = "";
onHackedData = "";
onDifferentData = "";
onUnsignedData = "";
regularCheck = "";
timeStampFormat = "none";
class Missions {
};
```

Using the default config.cfg from the official ArmA3 Dedicated Server wiki https://community.bistudio.com/wiki/Arma_3_Dedicated_Server#CONFIG_server.cfg its working with no problems.
(Deleted comments and stuff I don't use)

**Comment by JamieKG** [comment]
i just played with this and I believe its the voteMissionPlayers setting set it to 1 and you will get the mission selection screen

**Comment by alec-hs** [comment]
Yeah that would be it - if it is just you joining the sever to mission screen wouldn't display when it's set to 3. 3 means that 3 players need to be in server before mission screen shows up. 

You can override this by logging in as admin and manually bringing up the mission screen by typing this in any chat channel:
`#login password` 

Alternatively as JamieKG said - just lower it to 1.
