### ISSUE TITLE
Can't  use "Add mod from URL" and "Import from BIS Launcher" improt mods

### ISSUE THREAD

**Issue by Sakura-jun** [alec-hs/Flaxs-Arma-Server-Tool#57]
I get a windows:
An exception occurred:
Request aborted: Failed to create SSL/TLS secure channel.

**Comment by CALADARI** [comment]
Having same issue as the post starter , BTW the signature system seems changed on the last update ,so that is also a issue suggested to look into.

**Comment by CALADARI** [comment]
Having similar issue
`An exception occurred: Unable to connect to the remote server`

**Comment by alec-hs** [comment]
FAST is no longer supported - please move to FAST 2.x:
https://github.com/alec-hs/Flaxs-Arma-Server-Tool-2
