### ISSUE TITLE
Headless Clients not connecting

### ISSUE THREAD

**Issue by Cytreen** [alec-hs/Flaxs-Arma-Server-Tool#58]
When ever you have a server on a port other than 2302, the headless clients will not connect when launching a server. We need this kind of functionality as we run multiple server at the same time on our box.
Tested Ports
2312
2402
2502

**Comment by alec-hs** [comment]
Please switch to FAST 2 - see main page of this repo for link.

**Comment by Cytreen** [comment]
We are on FAST2

**Comment by alec-hs** [comment]
Could you please raise an issue on FAST 2 git.

https://github.com/alec-hs/Flaxs-Arma-Server-Tool-2
