### ISSUE TITLE
Creates broken basic.cfg

### ISSUE THREAD

**Issue by NeutraleNull** [alec-hs/Flaxs-Arma-Server-Tool#60]
After some big troubbles setting up my server i found out
that F.A.S.T is generating wrong basic.cfg files effectively breaking arma3 netcode.

The Problem in detail:

"MinErrorToSend=0,01;" is wrong because arma does understand ","
Arma can only parse float numbers when written with a ".".
Correct Version should be "MinErrorToSend=0.01;"

Here you can see what happens as a result to that error:
https://youtu.be/yt_IUOaeAPw

**Comment by alec-hs** [comment]
Hi, please switch to FAST2 - FAST is no longer supported and most of the issues with FAST have been addressed in FAST2. 

https://github.com/alec-hs/Flaxs-Arma-Server-Tool-2

**Comment by NeutraleNull** [comment]
That an error occurring in FAST2.
Oh i did not saw the git.
